import type { Metadata, Viewport } from "next";
import { JetBrains_Mono, Space_Grotesk } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { CommandPalette } from "@/components/CommandPalette";
import { ConsoleGreeting } from "@/components/ConsoleGreeting";
import { MotionProvider } from "@/components/MotionProvider";
import { themeInitScript } from "@/components/ThemeToggle";
import { profile } from "@/content/profile";

const display = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["500", "700"],
});

// Subset generated by scripts/subset-font.mjs (only glyphs the site uses).
const sans = localFont({
  src: "./fonts/pretendard-subset.woff2",
  variable: "--font-pretendard",
  weight: "400 700",
  display: "swap",
});

const mono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["400", "500"],
});

const title = `${profile.name} — 풀스택 개발자`;

export const metadata: Metadata = {
  metadataBase: new URL(profile.siteUrl),
  title: { default: title, template: `%s · ${profile.name}` },
  description: profile.tagline,
  openGraph: {
    type: "website",
    locale: "ko_KR",
    title,
    description: profile.tagline,
    url: "/",
    images: [{ url: "/og.png", width: 1200, height: 630, alt: `${profile.name} — Full-stack developer` }],
  },
  twitter: { card: "summary_large_image", title, description: profile.tagline, images: ["/og.png"] },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#0e100f" },
    { media: "(prefers-color-scheme: light)", color: "#f5f4ef" },
  ],
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="ko" className={`${sans.variable} ${display.variable} ${mono.variable}`} suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body>
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-50 focus:rounded-[3px] focus:bg-accent focus:px-4 focus:py-2 focus:text-accent-ink"
        >
          본문으로 건너뛰기
        </a>
        <MotionProvider>{children}</MotionProvider>
        <CommandPalette />
        <ConsoleGreeting />
      </body>
    </html>
  );
}
